#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
hour=0
while [ $hour -lt 13 ]; do
    echo Hour: $hour
    minute=1
	current=1
    while [ $minute -lt 60 ]; do
	echo $minute
	((minute = current + 1))
	((current = minute))
    done
    ((hour++))
done
